### ISSUE TITLE
Demo Lab Angular 2

### ISSUE THREAD

**Issue by alvaradopcesar** [Frontendpe/meetups#1]
Slides 5 min
Que es Typescript ... 5min
Instalando Angular 2 ( Demo ) 10min
Instalando Angular CLi ( Demo ) 10min
Agregando Angular Material. ( Demo ) 10min
Haciendo un App Web en vivo. ( Vivo ) . si la suerte y los dioses nos ayudan. 10min

**Comment by eporroa** [comment]
Hola @alvaradopcesar tienes algún email para contactarte?. Gracias!

**Comment by alvaradopcesar** [comment]
alvaradopcesar@gmail.com
