### ISSUE TITLE
JS del futuro traído al presente: Aurelia - Parte 1

### ISSUE THREAD

**Issue by paolocarrasco** [Frontendpe/meetups#3]
Agenda
======

- Contexto - *5 min*
  - ¿Qué es Aurelia?
  - ¿Por qué un framework del futuro?
- Comparación con otros framewoks - *20 min*
  - Hello World con Aurelia
  - Código de un formulario con Aurelia vs Vue.js vs Angular 2
- Demo de Large SPA = Brainy (desarrollado en Avantica) - *10 min*

Si le gusta a la gente, podemos hacer más sesiones para profundizar: testing, organización de código, buenas prácticas, web-components+slots, etc etc :smiley:

**Comment by andresclaros** [comment]
Hola Pablo, ya hicienron la conferencia?

**Comment by paolocarrasco** [comment]
Hola Andrés. Nada aún. Este mes voy a estar ocupado. Quizás en junio, si hay interés :smiley:

**Comment by hpneo** [comment]
@paolocarrasco para Junio estamos pensando armar un meetup de frameworks JS (el de Mayo queremos hacerlo sobre CSS). ¿Tienes un correo a donde podemos escribirte?

**Comment by paolocarrasco** [comment]
¡Buenísimo! Escríbeme a paolo.carrasco@gmail.com.
